find_path(SVTHEVC_INCLUDE_DIR NAMES "svt-hevc/EbSvtHevc.h" PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include" NO_DEFAULT_PATH)
find_library(SVTHEVC_LIBRARY_RELEASE NAMES SvtHevcDec SvtHevcEnc PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib" NO_DEFAULT_PATH)
find_library(SVTHEVC_LIBRARY_DEBUG   NAMES SvtHevcDec SvtHevcEnc PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug/lib" NO_DEFAULT_PATH)
if(NOT SVTHEVC_INCLUDE_DIR OR NOT (SVTHEVC_LIBRARY_RELEASE OR SVTHEVC_LIBRARY_DEBUG))
    message(FATAL_ERROR "Broken installation of vcpkg port svt-hevc")
endif()
if(CMAKE_VERSION VERSION_LESS 3.4)
    include(SelectLibraryConfigurations)
    select_library_configurations(SVTHEVC)
    unset(SVTHEVC_FOUND)
endif()
_find_package(${ARGS})
