find_path(SVTAV1_INCLUDE_DIR NAMES "svt-av1/EbSvtAv1.h" PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include" NO_DEFAULT_PATH)
find_library(SVTAV1_LIBRARY_RELEASE NAMES SvtAv1Dec SvtAv1Enc PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib" NO_DEFAULT_PATH)
find_library(SVTAV1_LIBRARY_DEBUG   NAMES SvtAv1Dec SvtAv1Enc PATHS "${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug/lib" NO_DEFAULT_PATH)
if(NOT SVTAV1_INCLUDE_DIR OR NOT (SVTAV1_LIBRARY_RELEASE OR SVTAV1_LIBRARY_DEBUG))
    message(FATAL_ERROR "Broken installation of vcpkg port svt-av1")
endif()
if(CMAKE_VERSION VERSION_LESS 3.4)
    include(SelectLibraryConfigurations)
    select_library_configurations(SVTAV1)
    unset(SVTAV1_FOUND)
endif()
_find_package(${ARGS})
